# Generated by Django 3.1.1 on 2020-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
                ('portfolio_link', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('on_the_job', models.BooleanField(default=False)),
                ('current_project', models.CharField(default='', max_length=50)),
                ('total_jobs', models.IntegerField(default=0)),
            ],
        ),
    ]
