# Generated by Django 3.1.1 on 2020-10-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
