# Generated by Django 3.1.1 on 2020-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='phone_num',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
