# Generated by Django 3.1.1 on 2020-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0006_auto_20201002_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='password',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='on_the_job',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
