# Generated by Django 3.1.1 on 2020-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='development_link_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='development_link',
            field=models.CharField(max_length=200),
        ),
    ]
