# Generated by Django 3.1.1 on 2020-10-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201001_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='development_link_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_hosting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='started_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='update_after_wireframes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='wireframes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='development_link',
            field=models.CharField(max_length=500),
        ),
    ]
