# Generated by Django 3.1.1 on 2020-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201001_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='development_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
