# Generated by Django 3.1.1 on 2020-09-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
