# Generated by Django 3.1.1 on 2020-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200926_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_number',
            field=models.CharField(default=False, max_length=32),
        ),
    ]
