# Generated by Django 3.1.1 on 2020-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone_num', models.CharField(default=0, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('time_slot', models.CharField(default=False, max_length=50)),
                ('site_type', models.CharField(default=False, max_length=50)),
                ('project', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
