# Generated by Django 3.1.1 on 2020-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='project_number',
            field=models.CharField(default=False, editable=False, max_length=32),
        ),
    ]
