# Generated by Django 3.1.1 on 2020-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project',
            field=models.TextField(max_length=500),
        ),
    ]
