# Generated by Django 3.1.1 on 2020-10-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20201002_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='password',
        ),
    ]
