# Generated by Django 3.1.1 on 2020-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_appointment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_for',
            field=models.BooleanField(default=False),
        ),
    ]
