# Generated by Django 3.0.5 on 2020-09-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_remove_consultation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
